// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABqM0HdoAZHamUD_GgGVx3T-MOllvXHsQ',
    appId: '1:626943139419:web:596027362fc06e322ae97e',
    messagingSenderId: '626943139419',
    projectId: 'tod0-6105a',
    authDomain: 'tod0-6105a.firebaseapp.com',
    storageBucket: 'tod0-6105a.appspot.com',
    measurementId: 'G-Y4BLPB9JMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRj4pMmBwhBmeDxbHrbv1jMMTQzS7gNrU',
    appId: '1:72993290016:android:fd6134767e8f176b8e0945',
    messagingSenderId: '72993290016',
    projectId: 'todo-52a72',
    storageBucket: 'todo-52a72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrICRjXQUF--sL6JZjMW_cteRcqvPKKoA',
    appId: '1:72993290016:ios:4c6082b4a8b29b248e0945',
    messagingSenderId: '72993290016',
    projectId: 'todo-52a72',
    storageBucket: 'todo-52a72.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5PfpIdwPmMM6-Dd6bTJRJgvpQc3CYQSE',
    appId: '1:626943139419:ios:6cbf9e0a41b32f5b2ae97e',
    messagingSenderId: '626943139419',
    projectId: 'tod0-6105a',
    storageBucket: 'tod0-6105a.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABqM0HdoAZHamUD_GgGVx3T-MOllvXHsQ',
    appId: '1:626943139419:web:5b9ac9531f95efd52ae97e',
    messagingSenderId: '626943139419',
    projectId: 'tod0-6105a',
    authDomain: 'tod0-6105a.firebaseapp.com',
    storageBucket: 'tod0-6105a.appspot.com',
    measurementId: 'G-02PHQWTY3K',
  );
}